---
name: Build bat
on:
  workflow_dispatch:
  push:
    branches:
      - master
permissions:
  contents: read
  id-token: write
jobs:
  build:
    name: Build
    strategy:
      matrix:
        include:
          - name: macos-amd64
            os: macos-latest
            arch: x86_64
          - name: linux-amd64
            os: ubuntu-latest
            arch: x86_64
    runs-on: "${{ matrix.os }}"
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          submodules: recursive
      - name: Build
        run: make RELEASE=1
      - name: Build wrapper
        run: make RELEASE=1 wrapper
      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: "${{ matrix.name }}"
          path: |
            build
            !build/*/*.o
