---
name: "Build bat"
on:
  push:
    branches:
      - master
permissions:
  contents: read
  id-token: write
jobs:
  build:
    strategy:
      matrix:
        include:
          - name: macos-amd64
            os: macos
            arch: x64
          - name: macos-arm64
            os: macos
            arch: arm64
          - name: linux-amd64
            os: linux
            arch: x64
    runs-on: [${{ matrix.os }}-latest, ${{ matrix.arch }}]
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: "Build"
        run: make RELEASE=1
      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: ${{ matrix.name }}
          path: |
            build
            !build/*/*.o
